const TYPES={A:'Asteroid',D:'Desert world',E:'Earth-like world',S:'Space station',W:'Waterworld'};
const GRAVITY={E:'Earth-like',H:'High',L:'Low',O:'Negligible / no gravity'};
const ATM={A:'Acclimatisation needed',C:'Corrosive',E:'Earth-like / breathable',I:'Inert',O:'No atmosphere',T:'Toxic',X:'Toxic and corrosive'};
const POP={1:'Less than a hundred',2:'A few hundreds',3:'Thousands',4:'Hundreds of thousands',5:'Millions',6:'Billions'};
const BIO={A:'Alien biosphere',E:'Human-compatible biosphere',O:'No biosphere'};
let state=loadState();let selected=null;
const $=id=>document.getElementById(id);
function emptyMap(mode='subsector',title='Untitled Map'){return {version:1,title,mode,hexes:{}}}
function key(q,r){return `${q},${r}`}
function rng(max){return Math.floor(Math.random()*max)+1}
function d6(){return rng(6)}function d10(){return rng(10)}
function rollWorld(){const roll=d6();const type=roll===1?'S':roll===2?'A':roll<=4?'E':roll===5?'D':'W';const g=d6();const gravity=type==='S'?'E':type==='A'?'O':g<=2?'L':g<=4?'E':'H';let atmosphere;if(type==='S')atmosphere='E';else if(type==='A')atmosphere='O';else{const a=d10();atmosphere=a===1?'I':a<=4?'A':a<=7?'E':a===8?'T':a===9?'C':'X'}let population=d6();if(type==='S'||type==='A')population=Math.ceil(population/2);let biosphere;if(type==='S'||type==='A')biosphere='O';else{const b=d6();biosphere=b===1?'O':b<=5?'E':'A'}return {kind:'world',name:'',type,gravity,atmosphere,population:String(population),biosphere,notes:''}}
function rollHex(){const roll=d6()+d6();if(roll===10||roll===12)return {kind:'anomaly',name:'Anomaly',notes:'Generated from 2d6 = '+roll};if(roll%2===1)return rollWorld();return {kind:'empty'}}
function dims(){return state.mode==='sector'?{cols:24,rows:30}:{cols:8,rows:10}}
function generate(){const {cols,rows}=dims();if(Object.values(state.hexes).some(h=>h.kind&&h.kind!=='empty')&&!$('confirmGenerate').checked){if(!confirm('Generate over the current map? Existing worlds will be replaced.'))return}state.hexes={};for(let r=0;r<rows;r++)for(let q=0;q<cols;q++)state.hexes[key(q,r)]=rollHex();save();render();toast(`Generated ${state.mode}.`)}
function setMode(mode){state.mode=mode;selected=null;save();render()}
function render(){$('mapTitle').value=state.title;$('mapMode').value=state.mode;$('workspaceTitle').textContent=state.title||'Untitled Map';const {cols,rows}=dims();$('workspaceMeta').textContent=`${cols} × ${rows} parsecs · ${Object.values(state.hexes).filter(h=>h.kind==='world').length} worlds`;const map=$('map');map.style.setProperty('--cols',cols);map.style.setProperty('--rows',rows);map.innerHTML='';for(let r=0;r<rows;r++)for(let q=0;q<cols;q++){const h=state.hexes[key(q,r)]||{kind:'empty'};const el=document.createElement('button');el.type='button';el.className=`hex ${h.kind||'empty'}${selected===key(q,r)?' selected':''}`;el.style.setProperty('--offset',q%2);el.dataset.key=key(q,r);if(h.kind==='world')el.dataset.type=h.type;el.title=tooltip(q,r,h);el.innerHTML=`<span class="coord">${coord(q,r)}</span><span class="symbol">${h.kind==='world'?(h.type==='S'?'◉':h.type==='A'?'✦':'●'):h.kind==='anomaly'?'✹':''}</span>${h.kind==='world'?`<span class="code">${code(h)}</span>`:''}${h.name?`<span class="name">${escapeHtml(h.name)}</span>`:''}`;el.addEventListener('click',()=>selectHex(key(q,r)));map.appendChild(el)}$('emptySelection').hidden=!!selected;$('hexEditor').hidden=!selected;if(selected)populateEditor(state.hexes[selected]||{kind:'empty'})}
function coord(q,r){return String.fromCharCode(65+q)+String(r+1).padStart(2,'0')}
function code(h){return `${h.type||'E'}${h.gravity||'E'}${h.atmosphere||'E'}${h.population||'1'}${h.biosphere||'O'}`}
function tooltip(q,r,h){if(h.kind==='world')return `${coord(q,r)} · ${h.name||'Unnamed world'} · ${code(h)} · ${TYPES[h.type]}`;if(h.kind==='anomaly')return `${coord(q,r)} · ${h.name||'Anomaly'}`;return `${coord(q,r)} · Empty`}
function selectHex(k){selected=k;render()}
function populateEditor(h){$('hexId').textContent=`Hex ${selected}`;$('hexKind').value=h.kind||'empty';$('worldFields').hidden=h.kind!=='world';$('anomalyFields').hidden=h.kind!=='anomaly';if(h.kind==='world'){$('worldName').value=h.name||'';$('planetCode').value=code(h);$('type').value=h.type||'E';$('gravity').value=h.gravity||'E';$('atmosphere').value=h.atmosphere||'E';$('population').value=h.population||'1';$('biosphere').value=h.biosphere||'O';$('worldNotes').value=h.notes||''}if(h.kind==='anomaly'){$('anomalyName').value=h.name||'';$('anomalyNotes').value=h.notes||''}}
function applyHex(){if(!selected)return;const kind=$('hexKind').value;if(kind==='empty')state.hexes[selected]={kind:'empty'};else if(kind==='anomaly')state.hexes[selected]={kind:'anomaly',name:$('anomalyName').value||'Anomaly',notes:$('anomalyNotes').value||''};else state.hexes[selected]={kind:'world',name:$('worldName').value||'',type:$('type').value,gravity:$('gravity').value,atmosphere:$('atmosphere').value,population:$('population').value,biosphere:$('biosphere').value,notes:$('worldNotes').value||''};save();render();toast('Hex updated.')}
function onCode(){const v=$('planetCode').value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,5);$('planetCode').value=v;if(v.length===5){if(TYPES[v[0]])$('type').value=v[0];if(GRAVITY[v[1]])$('gravity').value=v[1];if(ATM[v[2]])$('atmosphere').value=v[2];if(POP[v[3]])$('population').value=v[3];if(BIO[v[4]])$('biosphere').value=v[4]}}
function updateCode(){if($('hexKind').value==='world')$('planetCode').value=code({type:$('type').value,gravity:$('gravity').value,atmosphere:$('atmosphere').value,population:$('population').value,biosphere:$('biosphere').value})}
function save(){localStorage.setItem('astrovoyage-map',JSON.stringify(state));try{history.replaceState(null,'',location.pathname+'#map='+encodeURIComponent(btoa(unescape(encodeURIComponent(JSON.stringify(state))))))}catch(e){}}
function loadState(){try{if(location.hash.startsWith('#map=')){const raw=decodeURIComponent(location.hash.slice(5));return JSON.parse(decodeURIComponent(escape(atob(raw))))}const x=localStorage.getItem('astrovoyage-map');if(x)return JSON.parse(x)}catch(e){}return emptyMap()}
function download(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.title||'astrovoyage-map').replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json';a.click();URL.revokeObjectURL(a.href)}
async function share(){save();try{await navigator.clipboard.writeText(location.href);toast('Share link copied to clipboard.')}catch{toast('Share link is ready in the address bar.')}}
function toast(t){const x=$('toast');x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),2200)}
function escapeHtml(s){return String(s).replace(/[&<>\\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\\':'&#92;','"':'&quot;'}[c]))}
$('mapTitle').addEventListener('input',e=>{state.title=e.target.value;save();$('workspaceTitle').textContent=state.title||'Untitled Map'});$('mapMode').addEventListener('change',e=>setMode(e.target.value));$('generateBtn').addEventListener('click',generate);$('newSubsectorBtn').addEventListener('click',()=>{state=emptyMap('subsector','New Subsector');save();render()});$('newSectorBtn').addEventListener('click',()=>{state=emptyMap('sector','New Sector');save();render()});$('clearBtn').addEventListener('click',()=>{if(confirm('Clear this map?')){state=emptyMap(state.mode,state.title);save();render()}});$('shareBtn').addEventListener('click',share);$('applyHexBtn').addEventListener('click',applyHex);$('hexKind').addEventListener('change',()=>populateEditor({kind:$('hexKind').value}));$('planetCode').addEventListener('input',onCode);['type','gravity','atmosphere','population','biosphere'].forEach(id=>$(id).addEventListener('change',updateCode));$('exportBtn').addEventListener('click',download);$('copyJsonBtn').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(JSON.stringify(state));toast('Map JSON copied.')}catch{toast('Clipboard unavailable.')}});$('importInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{state=JSON.parse(r.result);selected=null;save();render();toast('Map imported.')}catch{toast('Invalid map JSON.')}};r.readAsText(f)});
render();